apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-nodejs
  labels:
    app: nodejs-deploy 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          imagePullPolicy: Always
          image: nginx
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu:  "200m"






