apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    type: dev
spec:
  selector:
    app: node
    type: prod
  ports: 
      - nodePort: 32000
        port: 3000
        targetPort: 3000
  type: NodePort